version: '3.5'

services:
  gluster:
    image: gluster
    privileged: true
    environment:
      - NET_IFACE=eth0
    networks:
      - boh
    volumes:
      - /gluster:/log:ro,shared

networks:
  boh:
    external: true
